[default_session]
startup_command = "tmux rename-window 'editor' && nvim"

[[session]]
name = "PrintApp"
path = "~/Code/sites/printapp"
startup_script = "~/.config/sesh/scripts/laravel-watch.sh"

[[session]]
name = "EdiTracker"
path = "~/Code/sites/editracker"
startup_script = "~/.config/sesh/scripts/laravel.sh"

[[session]]
name = "DocumentLookup"
path = "~/Code/sites/documentlookup"
startup_script = "~/.config/sesh/scripts/laravel.sh"

[[session]]
name = "Buckets"
path = "~/Code/sites/buckets"
startup_script = "~/.config/sesh/scripts/laravel.sh"
