[default_session]
startup_command = "tmux rename-window 'Editor' && nvim"

[[session]]
name = "PrintApp"
path = "~/Code/sites/printapp"
startup_script = "~/.config/sesh/scripts/laravel.sh printapp"

[[session]]
name = "EdiTracker"
path = "~/Code/sites/editracker"
startup_script = "~/.config/sesh/scripts/laravel.sh editracker"

[[session]]
name = "DocumentLookup"
path = "~/Code/sites/documentlookup"
startup_script = "~/.config/sesh/scripts/laravel.sh documentlookup"

[[session]]
name = "Buckets"
path = "~/Code/sites/buckets"
startup_script = "~/.config/sesh/scripts/laravel.sh buckets"

[[session]]
name = "ECO"
path = "~/Code/sites/engineering-change-request"
startup_script = "~/.config/sesh/scripts/laravel-mailpit.sh"
