[general]
live_config_reload = true

# if env("COLOR_SCHEME") == "tokyonight" {
    import = [ "themes/tokyonight.toml" ]
# } else {
#     import = [ "themes/catppuccin-mocha.toml" ]
# }

[env]
term = "xterm-256color"

[window]
opacity = 1.0
decorations = "None"
padding = { x = 2, y = 6 }

[font]
normal = { family = "JetBrainsMono NFM", style = "Thin" }
bold = { family = "JetBrainsMono NFM", style = "SemiBold" }
italic = { family = "JetBrainsMono NFM", style = "Thin Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "SemiBold Italic" }
size = 13.0

[mouse]
hide_when_typing = true

[terminal]
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
