#!/usr/bin/env bash

systemctl --user daemon-reload

systemctl --user enable kanata.service

# Install Tmux Plugins
mkdir -p ~/.tmux/plugins/
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/scripts/install_plugins.sh

chsh --shell /bin/zsh "$USER"

echo "Installation complete ... restart recommended"
