[data.colors]
name = "ayu"
foreground = "#bfbdb6"
background = "#0b0e14"
black = "#11151c"
bright_black = "#686868"
red = "#ea6c73"
bright_red = "#f07178"
green = "#7fd962"
bright_green = "#aad94c"
yellow = "#f9af4f"
bright_yellow = "#ffb454"
blue = "#53bdfa"
bright_blue = "#59c2ff"
magenta = "#cda1fa"
bright_magenta = "#d2a6ff"
cyan = "#90e1c6"
bright_cyan = "#95e6cb"
white = "#c7c7c7"
bright_white = "#ffffff"
extended_16 = "#ff8f40"
extended_17 = "#d95757"

base00 = "#0b0e14"
base01 = "#131721"
base02 = "#202229"
base03 = "#3e4b59"
base04 = "#565b66"
base05 = "#bfbdb6"
base06 = "#e6e1cf"
base07 = "#f3f4f5"
base08 = "#f07178"
base09 = "#ff8f40"
base0A = "#ffb454"
base0B = "#aad94c"
base0C = "#95e6cb"
base0D = "#59c2ff"
base0E = "#d2a6ff"
base0F = "#e6b450"
