abbr --add ansb ansible
abbr --add aconf ansible-config
abbr --add acon ansible-console
abbr --add aver ansible-version
abbr --add arinit ansible-role-init
abbr --add aplaybook ansible-playbook
abbr --add ainv ansible-inventory
abbr --add adoc ansible-doc
abbr --add agal ansible-galaxy
abbr --add apull ansible-pull
abbr --add aval ansible-vault
