format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

right_format = """
$python\
"""

add_newline = false

[directory]
style = "blue"
truncation_length = 17
truncation_symbol = "  "
home_symbol = " 󰜥"

[os]
disabled = false

[os.symbols]
Arch = " "
Pop = " "
Ubuntu = " "
Garuda = " "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[username]
format = "[$user]($style)"

[hostname]
format = "@[$hostname]($style) "
style = "bold dimmed green"

[git_branch]
format = "[$symbol$branch ]($style)"
style = "green"
symbol = " "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-blue"

[php]
style = "bright-purple"
format = "[$symbol($version)]($style)"
version_format = "${raw}"
symbol = " "
