# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = hyprctl setcursor Breeze 24

# -- Wallpaper
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/rotate_hyprpaper.sh&

# Cliphist
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# -- Udiskie for mount stuff
exec-once = udiskie --tray &

# -- Polkit
exec-once = systemctl --user start hyprpolkitagent

# KDE Walle exec-once = uwsm app -- /usr/lib/pam_kwallet_init

# -- Bar
# exec-once = waybar
exec-once = hyprpanel

# -- Idle Control
exec-once = hypridle

# -- Onedrive
# exec-once = test -x "$(which onedrive)" && onedrive --monitor

# Plugins
exec-once = /usr/bin/pypr
