# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = nm-applet
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1

# -- Wallpaper
exec-once=hyprpaper
exec-once = ~/.config/hypr/scripts/rotate_hyprpaper.sh&

# Cliphist
exec-once = wl-paste --type text  --watch ~/go/bin/cliphist store
exec-once = wl-paste --type image --watch ~/go/bin/cliphist store

# Cliphist
exec-once = wl-paste --type text  --watch ~/.go/bin/cliphist store
exec-once = wl-paste --type image --watch ~/.go/bin/cliphist store

# -- Udiskie for mount stuff
exec-once = udiskie --tray &

# -- Blueman
exec-once = blueman-applet

# -- PaSystray
exec-once = pasystray
# -- PaSystray
exec-once = pasystray

# -- Polkit
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# -- Notifications
exec-once = dunst
# -- Bar
exec-once = waybar
# -- Idle Control
exec-once = hypridle

# -- Onedrive
exec-once = test -x "$(which onedrive)" && onedrive --monitor

# Plugins
exec-once = pypr
