# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# -- Keyring
# no need to launch, using pam to start gnome keyring
# exec-once = kwalletmanager6 &
# exec-once = sleep 1; /usr/lib/pam_kwallet_init --no-startup-id
# exec-once = sleep 2; hyprctl dispatch closewindow org.kde.kwalletmanager6

# -- Udiskie for mount stuff
exec-once = udiskie --tray &

# -- Blueman
exec-once = blueman-applet

# -- Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
# -- Wallpaper
exec-once=hyprpaper
exec-once = ~/.config/hypr/scripts/rotate_hyprpaper.sh&
# -- Notifications
exec-once = dunst
# -- Bar
exec-once = waybar
# -- Idle Control
exec-once = hypridle
# -- Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store;
exec-once = wl-paste --type image --watch cliphist store
# -- Background Apps
#exec-once = nm-applet
# -- Mouse Helper
exec-once = ckb-next --background
# -- Pyprland Plugin
exec-once = pypr
