decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    blur {
        enabled = true
        size = 5
        passes = 1
    }

    drop_shadow = true
    shadow_range = 2
    shadow_render_power = 1
    col.shadow = rgba(585b70aa)
    # dim_inactive = true
    # dim_strength = 0.15
}


