general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 6
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(94e2d5ee) rgba(89dcebee) 45deg
    col.inactive_border = rgba(45475aaa)

    layout = master

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    # cursor_inactive_timeout = 15

    # no_cursor_warps = true
}


