# Monitor Configs
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=desc:Dell Inc. DELL S3220DGF CMCSF43,2560x1440@164.056000,auto,1

# Default Monitor Settings
monitor=,preferred,auto,1

