# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = tile, class:(Google-chrome), title:(Outlook)
windowrulev2 = tile, class:(Google-chrome), title:(Microsoft Teams)
windowrulev2 = float, class:(org.remmina.Remmina), title:(Remmina Remote Desktop Client)
windowrulev2 = float, class:(Bitwarden), title:(Bitwarden)
windowrulev2 = float, title:^(Virtual Machine Manager)$
windowrulev2 = float,class:(udiskie)

