# Turn on the mouse
set -g mouse on

# automatically renumber tmux windows
set -g renumber-windows on

# unbind default prefix and set it to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# for nested tmux sessions
bind-key a send-prefix

# Activity Monitoring
set -g monitor-activity off
set -g visual-activity off

# tile all windows
unbind =
bind = select-layout tiled

# make window/pane index start with 1
set -g base-index 1
set -g pane-base-index 1

# Rename Pane with Tail of working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

######################
#### Key Bindings ####
######################

# split window and fix path for tmux 1.9
bind v split-window -h -c "#{pane_current_path}" -p 25
bind s split-window -v -c "#{pane_current_path}" -p 25

unbind '"'
unbind %

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind M-g split-window -h -c "#{pane_current_path}" lazygit

# Toggle status bar
bind S set status

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# set vi mode for copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-toggle

# version_pat='s/^tmux[^0-9]*([.0-9]+).*/\1/p'

# is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
#     | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
# bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
# bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
# bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
# bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
# tmux_version="$(tmux -V | sed -En "$version_pat")"
# setenv -g tmux_version "$tmux_version"

# if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
#   "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
# if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \

# bind-key -T copy-mode-vi C-h select-pane -L
# bind-key -T copy-mode-vi C-j select-pane -D
# bind-key -T copy-mode-vi C-k select-pane -U
# bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\\ select-pane -l
bind-key -n "C-\\" if-shell "$is_vim" "send-keys C-\\\\"  "select-pane -l"

# Tmux Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "shadkaske/tokyo-night-tmux"
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @tilish-dmenu 'on'
set -g @tilish-navigate 'on'
set -g @tilish-default 'main-horizontal'

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-boot 'off'
set -g @continuum-restore 'off'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

run '~/.tmux/plugins/tpm/tpm'

