return {
  'catppuccin/nvim',
  priority = 1000,
  name = 'catppuccin',
  opts = {
    flavor = 'auto',
    integrations = {
      aerial = true,
      bufferline = true,
      cmp = true,
      fidget = true,
      gitsigns = true,
      harpoon = true,
      indent_blankline = true,
      leap = true,
      lsp_trouble = true,
      mason = true,
      mini = true,
      navic = false,
      noice = true,
      notify = true,
      nvimtree = true,
      telescope = true,
      treesitter = true,
      treesitter_context = true,
      which_key = true,
      window_picker = true,
    },
  },
}
