return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    animate = { enabled = true },
    bigfile = { enabled = true },
    bufdelete = { enabled = true },
    dashboard = { enabled = true },
    lazygit = { enabled = true },
    notifier = { enabled = true },
    notify = { enabled = true },
    quickfile = { enabled = true },
    rename = { enabled = true },
    scroll = { enabled = true },
    toggle = { enabled = true },
    words = { enabled = true },
  },
  keys = {
    { "<leader>gg", function() require('snacks').lazygit() end,          desc = "Lazygit" },
    { "<leader>gf", function() require('snacks').lazygit.log_file() end, desc = "Lazygit Current File History" },
    { "<leader>gl", function() require('snacks').lazygit.log() end,      desc = "Lazygit Log (cwd)" },
    { "<leader>bd", function() require('snacks').bufdelete() end,        desc = "Delete Buffer" },
  },
}
