version: "3"
networks:
  sail:
    external: true
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PUID: 1000
      PGID: 1000
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

