font_family         JetBrainsMono NFM Thin
italic_font         JetBrainsMono NFM Thin Italic
bold_font           JetBrainsMono NFM SemiBold
bold_italic_font    JetBrainsMono NFM SemiBold Italic
font_size           12.0

modify_font cell_height 3px

dynamic_background_opacity yes
background_opacity  1.0

enable_audio_bell    no

copy_on_select       yes

hide_window_decorations yes

remember_window_size no
initial_window_width 124c
initial_window_height 32c
placement_strategy center

strip_trailing_spaces smart

confirm_os_window_close 0

window_padding_width 4

sync_to_monitor yes

tab_bar_min_tabs            2
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

map ctrl+shift+f1 set_background_opacity default
map ctrl+shift+f2 set_background_opacity +0.01
map ctrl+shift+f3 set_background_opacity -0.01
map ctrl+shift+z toggle_layout stack
map ctrl+a>r set_tab_title
map ctrl+a>c new_tab

include tokyonight_night.conf

# vim:ft=conf
